name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'node'

      - name: Install dependencies
        run: node install

      - name: Build
        run: node build

      - name: Lint
        run: node lint

      - name: Dev
        run: node dev

      - name: Test
        run: node test
